# Generated by Django 5.2.8 on 2025-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("leads_shortlisted", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("responses_received", models.IntegerField(default=0)),
                ("goals_achieved", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("project_interest", models.CharField(max_length=100)),
                ("budget", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Connected", "Connected"),
                            ("Not Connected", "Not Connected"),
                            ("Visit Scheduled", "Visit Scheduled"),
                            ("Purchased", "Purchased"),
                            ("Not Interested", "Not Interested"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_contact_date", models.DateField()),
            ],
        ),
    ]
