# Generated by Django 5.2.8 on 2025-11-21 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_campaignconfig_sentmessage_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="last_conversation_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="unit_type",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated unit types: studio, 1 bed, 2 bed, etc.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
