# Generated by Django 5.2.8 on 2025-11-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_lead_created_at_lead_last_conversation_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="appointment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="financing_option",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="purchase_motive",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="sent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_turns",
                to="api.sentmessage",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("not_interested", "Not Interested"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="unit_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="ScheduledVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                ("last_conversation_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_visits",
                        to="api.campaignconfig",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_visits",
                        to="api.lead",
                    ),
                ),
            ],
        ),
    ]
