# Generated by Django 5.2.8 on 2025-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_conversation_appointment_date_lead_financing_option_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followup_interval_days", models.IntegerField(default=3)),
                ("max_followups", models.IntegerField(default=5)),
                (
                    "messaging_focus",
                    models.CharField(
                        default="Property Features & Benefits", max_length=100
                    ),
                ),
                (
                    "response_style",
                    models.CharField(default="Professional & Formal", max_length=100),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        default="Medium - Moderate urgency", max_length=100
                    ),
                ),
                ("custom_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "AI Agent Settings",
            },
        ),
    ]
