# Generated by Django 5.2.8 on 2025-11-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_aiagentsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignconfig",
            name="leads_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="conversation_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("waiting_response", "Waiting for Response"),
                    ("goal_achieved", "Goal Achieved"),
                    ("stopped", "Stopped"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
